// <auto-generated />
namespace PortfolioRebuild.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedLMLSeedData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedLMLSeedData));
        
        string IMigrationMetadata.Id
        {
            get { return "201812031912459_AddedLMLSeedData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
